### ISSUE TITLE
Issue with fromMatrix under the hood

### ISSUE THREAD

**Issue by delabj** [domagal9/backbone#32] opened 2021-07-13 23:19 UTC
Just did a fresh install on a computer to do several networks all at once and am now getting the error "Error in frommatrix(backbone, class): object 'G' not found"

I'm attaching a minimal reprex to show what's happening. I'm not 100% sure what's happening, but I believe in frommatrix there must be a case where G is not set causing the function to fail. 

https://github.com/domagal9/backbone/blob/master/R/model.helpers.R

``` r
library(backbone)
#>  ____
#> |  _ \   backbone v1.5.0
#> |#|_) |  Cite: Domagalski, R., Neal, Z. P., & Sagan, B. (2021). Backbone: An
#> |# _ <         R package for extracting the backbone of bipartite projections.
#> |#|_) |        PLoS ONE. https://doi.org/10.1371/journal.pone.0244363
#> |____/   For help: type vignette("backbone"); email zpneal@msu.edu; github domagal9/backbone
tmp <- backbone::sdsm(davis)
#> This matrix object looks like an unweighted bipartite network of 18 agents and 14 artifacts.
backbone.extract(tmp)
#> Error in frommatrix(backbone, class): object 'G' not found
```

<sup>Created on 2021-07-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by delabj** [comment] 2021-07-13 23:41
When looking at the code, I think backbone.extract is passing the value 1 as  the class to `frommatrix` leaving that chain of logic without an output that produces a G. 

I believe the culprit is on line 97 of sdsm 
```{r}
  b <- c("Stochastic Degree Sequence Model", convert$summary$class, convert$summary$bipartite, convert$summary$symmetric, convert$summary$weighted, dim(B)[1], dim(B)[2])
```

At this point in the function ` convert$summary$class` is a factor so when it's silently coerced to text here, it's changing that factor of level "matrix" to a 1. 

This can be solved in this line by modifying  it to read
```{r}
  b <- c("Stochastic Degree Sequence Model", as.character( convert$summary$class), convert$summary$bipartite, convert$summary$symmetric, convert$summary$weighted, dim(B)[1], dim(B)[2])
```

Which may be a bit inelegant

**Comment by zpneal** [comment] 2021-07-14 12:02
Thanks for pointing this out. I tried, but wasn't able to reproduce the error you were seeing:
```
> library(backbone)
 ____  
|  _ \   backbone v1.5.0
|#|_) |  Cite: Domagalski, R., Neal, Z. P., & Sagan, B. (2021). Backbone: An
|# _ <         R package for extracting the backbone of bipartite projections. 
|#|_) |        PLoS ONE. https://doi.org/10.1371/journal.pone.0244363
|____/   For help: type vignette("backbone"); email zpneal@msu.edu; github domagal9/backbone
> tmp <- backbone::sdsm(davis)
This matrix object looks like an unweighted bipartite network of 18 agents and 14 artifacts.
> backbone.extract(tmp)
          EVELYN LAURA THERESA BRENDA CHARLOTTE FRANCES ELEANOR PEARL RUTH VERNE MYRNA KATHERINE SYLVIA NORA HELEN DOROTHY
EVELYN         0     0       0      0         0       0       0     0    0     0     0         0      0    0     0       0
LAURA          0     0       0      0         0       0       0     0    0     0     0         0      0    0     0       0
THERESA        0     0       0      0         0       0       0     0    0     0     0         0      0    0     0       0
BRENDA         0     0       0      0         0       0       0     0    0     0     0         0      0    0     0       0
CHARLOTTE      0     0       0      0         0       0       0     0    0     0     0         0      0    0     0       0
FRANCES        0     0       0      0         0       0       0     0    0     0     0         0      0    0     0       0
ELEANOR        0     0       0      0         0       0       0     0    0     0     0         0      0    0     0       0
PEARL          0     0       0      0         0       0       0     0    0     0     0         0      0    0     0       0
RUTH           0     0       0      0         0       0       0     0    0     0     0         0      0    0     0       0
VERNE          0     0       0      0         0       0       0     0    0     0     0         0      0    0     0       0
MYRNA          0     0       0      0         0       0       0     0    0     0     0         0      0    0     0       0
KATHERINE      0     0       0      0         0       0       0     0    0     0     0         0      0    0     0       0
SYLVIA         0     0       0      0         0       0       0     0    0     0     0         0      0    0     0       0
NORA           0     0       0      0         0       0       0     0    0     0     0         0      0    0     0       0
HELEN          0     0       0      0         0       0       0     0    0     0     0         0      0    0     0       0
DOROTHY        0     0       0      0         0       0       0     0    0     0     0         0      0    0     0       0
OLIVIA         0     0       0      0         0       0       0     0    0     0     0         0      0    0     0       0
FLORA          0     0       0      0         0       0       0     0    0     0     0         0      0    0     0       0
          OLIVIA FLORA
EVELYN         0     0
LAURA          0     0
THERESA        0     0
BRENDA         0     0
CHARLOTTE      0     0
FRANCES        0     0
ELEANOR        0     0
PEARL          0     0
RUTH           0     0
VERNE          0     0
MYRNA          0     0
KATHERINE      0     0
SYLVIA         0     0
NORA           0     0
HELEN          0     0
DOROTHY        0     0
OLIVIA         0     0
FLORA          0     0
```

You mentioned this was a clean install of the package. Was it from CRAN using `install.packages("backbone")`? Can you provide any additional details on the version of R you're running, or your OS?

**Comment by delabj** [comment] 2021-07-14 12:13
Hey there, thanks for getting back so quickly. 

I was using the CRAN version as well as the Github version

I initially got this error on my windows machine with R 3.6.x (not near it atm for exact version) I'm mid project so I haven't taken an update. I must have run the reprex without the session_info  :/ 

Given what I found fixed it, I think this may be an issue introduced with R 4.0.0 where the default for stringsAsFactors argument indata.frame and read.table was changed to FALSE. [change log](https://cran.r-project.org/doc/manuals/r-devel/NEWS.html) This is easily fixed by explicitly setting this to FALSE in data.frame calls in functions and would enable the package to function on older versions of R.

**Comment by zpneal** [comment] 2021-07-14 12:47
I think you're right about the stringsAsFactors issue, since I'm not getting the error running on R 4.0.2. We'll get that updated in the next CRAN release to make sure it's backward compatible. Thanks again!

**Comment by delabj** [comment] 2021-07-14 12:51
No problem! I left a pull request of what got it working locally for me last night, as well as some changes that made the tests not fail. I hope that it's helpful!

**Comment by zpneal** [comment] 2021-07-16 12:44
I think this is fixed now, with changes implemented in the develop branch. Thanks!

**Closed by zpneal** 2021-07-16 12:44 UTC
